### ISSUE TITLE
_LLAMA

### ISSUE THREAD

**Issue by vtwoptwo** [thehitchhikersguideto/bookworms#27]
https://github.com/shawwn/llama-dl

**Comment by vtwoptwo** [comment]
currently downloading parameteres n weights

**Comment by ismadoukkali** [comment]
Amazing. Keep us on the loop!

**Comment by ismadoukkali** [comment]
Check this tweet, might be insightful: https://twitter.com/iamgingertrash/status/1636180818606592000?s=20

**Comment by ismadoukkali** [comment]
I have also just gotten early access to GPT 4.0 API. 8k tokens can fit a lot of info. Guys, check what Zane discussed in #28

**Comment by vtwoptwo** [comment]
not allowed without license so I am closing this issue for now
