### ISSUE TITLE
Define project scope, naming conventions and main goals (business goals)

### ISSUE THREAD

**Issue by vtwoptwo** [thehitchhikersguideto/bookworms#6]

**Comment by ismadoukkali** [comment]
Got it! Working on it.

**Comment by vtwoptwo** [comment]
hey! In the readme i added a section about the project separated into the what, the why and the how. Once you are done defining everything you can add it to the readme.

@ismadoukkali

**Comment by ismadoukkali** [comment]
Adding now - I filled out your outline.

**Comment by ismadoukkali** [comment]
I believe this has been discussed and tasks are well set.
