### ISSUE TITLE
Configure API

### ISSUE THREAD

**Issue by vtwoptwo** [thehitchhikersguideto/bookworms#7]

**Comment by vtwoptwo** [comment]
guys goodreads api is depreciated: 

@ZaneReda check the following apis and let me know which one u think is the best 
https://gist.github.com/anwarmontasir/bb8ab501163168c5149bb19d1bac95f9

**Comment by ismadoukkali** [comment]
We are web scraping all the data at the end. API wasn't up to date with the website's elements.
